apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-backend
  template:
    metadata:
      labels:
        app: travel-backend
    spec:
      containers:
        - name: travel-backend
          image: travel-backend:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: travel-backend-service
spec:
  type: ClusterIP
  selector:
    app: travel-backend
  ports:
    - port: 5000
      targetPort: 5000
