apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-frontend
  template:
    metadata:
      labels:
        app: travel-frontend
    spec:
      containers:
        - name: travel-frontend
          image: travel-frontend:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: travel-frontend-service
spec:
  type: NodePort
  selector:
    app: travel-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
